# Generated by Django 4.0.1 on 2022-04-14 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='buyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_invoice', to='webapp.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoices',
            name='product',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invoices',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seller_invoice', to='webapp.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoices',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
